@startuml
class ParticipantItemViewModel {
    + Id : Guid <<get>> <<set>>
    + Nickname : string <<get>> <<set>>
    + AvatarId : Guid? <<get>> <<set>>
    + SpecialField : string <<get>> <<set>>
}
class CourseParticipantsViewModel {
    + CourseId : Guid <<get>> <<set>>
    + CourseTitle : string <<get>> <<set>>
    + IsOwnerOrAdmin : bool <<get>> <<set>>
    + Owner : ParticipantItemViewModel <<get>> <<set>>
    + EnrolledStudents : List<ParticipantItemViewModel> <<get>> <<set>>
    + PendingStudents : List<ParticipantItemViewModel> <<get>> <<set>>
    + BannedStudents : List<ParticipantItemViewModel> <<get>> <<set>>
}
@enduml
