@startuml
class CourseCardViewModel {
    + Id : Guid <<get>> <<set>>
    + Title : string <<get>> <<set>>
    + CategoryName : string <<get>> <<set>>
    + OwnerNickname : string <<get>> <<set>>
    + StudentsCount : int <<get>> <<set>>
    + BannerId : Guid? <<get>> <<set>>
    + AverageGrade : double? <<get>> <<set>>
    + IsTeacherView : bool <<get>> <<set>>
}
@enduml
