@startuml
class CourseManagementViewModel {
    + Id : Guid <<get>> <<set>>
    + Title : string <<get>> <<set>>
    + Description : string <<get>> <<set>>
    + Pass : string? <<get>> <<set>>
    + IsPublic : bool <<get>> <<set>>
    + Category : CourseCategory <<get>> <<set>>
    + BannerId : Guid? <<get>> <<set>>
}
@enduml
