@startuml
class CourseDetailsViewModel {
    + Id : Guid <<get>> <<set>>
    + Title : string <<get>> <<set>>
    + Description : string <<get>> <<set>>
    + BannerId : Guid? <<get>> <<set>>
    + Category : CourseCategory <<get>> <<set>>
    + IsPublic : bool <<get>> <<set>>
    + IsGuest : bool <<get>> <<set>>
    + IsStudent : bool <<get>> <<set>>
    + IsOwnerOrAdmin : bool <<get>> <<set>>
    + IsUserBanned : bool <<get>> <<set>>
    + IsUserPending : bool <<get>> <<set>>
    + IsUserEnrolled : bool <<get>> <<set>>
}
@enduml
