@startuml
class TaskItemViewModel {
    + Id : Guid <<get>> <<set>>
    + Title : string <<get>> <<set>>
    + Deadline : DateTime? <<get>> <<set>>
    + Status : string <<get>> <<set>>
    + GradeString : string <<get>> <<set>>
    + MaxPoints : int <<get>> <<set>>
}
class FileItemViewModel {
    + Id : Guid <<get>> <<set>>
    + FileName : string <<get>> <<set>>
    + ReadableSize : string <<get>> <<set>>
}
class LessonItemViewModel {
    + Id : Guid <<get>> <<set>>
    + Title : string <<get>> <<set>>
    + AverageGrade : double? <<get>> <<set>>
    + Files : List<FileItemViewModel> <<get>> <<set>>
    + Tasks : List<TaskItemViewModel> <<get>> <<set>>
}
class CourseLessonsViewModel {
    + CourseId : Guid <<get>> <<set>>
    + CourseTitle : string <<get>> <<set>>
    + IsOwnerOrAdmin : bool <<get>> <<set>>
    + Lessons : List<LessonItemViewModel> <<get>> <<set>>
}
@enduml
