@startuml
class LessonDetailsViewModel {
    + CourseId : Guid <<get>> <<set>>
    + CourseTitle : string <<get>> <<set>>
    + LessonId : Guid <<get>> <<set>>
    + LessonTitle : string <<get>> <<set>>
    + LessonInfo : string <<get>> <<set>>
    + AverageGrade : double? <<get>> <<set>>
    + IsOwnerOrAdmin : bool <<get>> <<set>>
    + IsPublic : bool <<get>> <<set>>
    + Files : List<FileItemViewModel> <<get>> <<set>>
    + Tasks : List<TaskItemViewModel> <<get>> <<set>>
    + CourseStudents : List<ParticipantItemViewModel> <<get>> <<set>>
    + AllowedStudentIds : List<Guid> <<get>> <<set>>
}
@enduml
