@startuml
class NotificationItemViewModel {
    + Id : Guid <<get>> <<set>>
    + Title : string <<get>> <<set>>
    + Message : string <<get>> <<set>>
    + CreatedAt : DateTime <<get>> <<set>>
    + IsRead : bool <<get>> <<set>>
}
class NotificationGroupViewModel {
    + Date : DateTime <<get>> <<set>>
    + Notifications : List<NotificationItemViewModel> <<get>> <<set>>
}
class NotificationIndexViewModel {
    + GroupedNotifications : List<NotificationGroupViewModel> <<get>> <<set>>
    + SearchString : string? <<get>> <<set>>
}
@enduml
