@startuml
class UserProfileViewModel {
    + Id : Guid <<get>> <<set>>
    + Login : string <<get>> <<set>>
    + Nickname : string <<get>> <<set>>
    + Email : string <<get>> <<set>>
    + Info : string <<get>> <<set>>
    + LastLogin : DateTime <<get>> <<set>>
    + AvatarId : Guid? <<get>> <<set>>
    + Role : UserRole <<get>> <<set>>
    + SpecialFieldLabel : string? <<get>> <<set>>
    + SpecialFieldValue : string? <<get>> <<set>>
    + IsOwnProfile : bool <<get>> <<set>>
    + IsAdmin : bool <<get>> <<set>>
    + CurrentPassword : string? <<get>> <<set>>
}
@enduml
