@startuml
interface IAttachable {
    Attachments : List<FileModel> <<get>> <<set>>
    HasAttachments : bool <<get>>
    AttachFile(file:FileModel) : void
    RemoveFile(file:FileModel) : bool
    GetAttachments() : List<FileModel>
    IsAttachmentAllowed() : bool
}
@enduml
