@startuml
class Admin {
    + AccessLevel : bool <<get>> <<set>> = true
    + Admin(login:string, password:string, nickname:string, email:string)
    + CreateUser(login:string, password:string, nickname:string, email:string, role:UserRole) : User
    + EditUserFields(target:User, newLogin:string, newPassword:string, newNickname:string, newEmail:string, newAvatar:FileModel?, newInfo:string, specialValue:string?) : void
    + BlockUser(target:User) : bool
    + UnblockUser(target:User) : bool
    + EditCourse(course:Course, title:string, desc:string, banner:FileModel?, category:CourseCategory, pass:string?) : void
    + AcceptStudent(student:Student, course:Course) : void
    + BanStudent(student:Student, course:Course) : void
    + RemoveStudent(student:Student, course:Course) : void
    + CreateLesson(course:Course, title:string, text:string) : Lesson
    + EditLesson(lesson:Lesson, title:string, text:string, isPublic:bool, files:List<FileModel>) : void
    + DeleteLesson(course:Course, lesson:Lesson) : void
    + CreateTask(lesson:Lesson, title:string, theory:string, maxPoints:int, deadline:DateTime?, isVisible:bool, files:List<FileModel>) : Task
    + EditTask(task:Task, title:string, theory:string, maxPoints:int, deadline:DateTime?, isVisible:bool, files:List<FileModel>) : void
    + DeleteTask(lesson:Lesson, task:Task) : void
    + SetAccessibility(target:object, allowedStudents:List<Student>) : void
    + DeleteCourse(course:Course) : void
    + UnbanStudent(student:Student, course:Course) : void
    + RejectStudent(student:Student, course:Course) : void
}
User <|-- Admin
@enduml
