@startuml
class Course {
    + Id : Guid <<get>>
    + OwnerId : Guid <<get>> <<set>>
    + <<virtual>> Owner : Teacher <<get>> <<set>>
    + Title : string <<get>> <<set>>
    + Description : string <<get>> <<set>>
    + Banner : FileModel? <<get>> <<set>>
    + IsPublic : bool <<get>> <<set>>
    + Pass : string? <<get>> <<set>>
    + Category : CourseCategory <<get>> <<set>>
    + Students : List<Student> <<get>> <<set>>
    + PendingStudents : List<Student> <<get>> <<set>>
    + BannedStudents : List<Student> <<get>> <<set>>
    + Lessons : List<Lesson> <<get>> <<set>>
    + SearchKey : string <<get>> <<set>>
    + Tags : List<string> <<get>> <<set>>
    + Course()
    + UpdateCourseInfo(title:string, description:string, banner:FileModel?, category:CourseCategory, pass:string?) : void
    + VerifyCoursePassword(inputPassword:string) : bool
    + ProcessEnrollmentRequest(student:Student, password:string?) : bool
    + AddToPending(student:Student) : void
    + ActivateStudent(student:Student) : void
    + ExcludeStudent(student:Student) : void
    + AddToBanList(student:Student) : void
    + AddLesson(lesson:Lesson) : void
    + RemoveLesson(lesson:Lesson) : void
    + GetFilteredContent(student:Student) : List<Lesson>
    + GetGlobalAverage() : double
    + MatchSearch(query:string) : bool
    + GetSearchResultData() : SearchItem
    + GetSearchWeight(query:string) : int
    + RemoveFromBanList(student:Student) : void
    + RemoveFromPending(student:Student) : void
}
ISearchable <|-- Course
@enduml
