@startuml
class NotificationMessage {
    + Id : Guid <<get>>
    + Recipient : User <<get>>
    + Title : string <<get>>
    + Message : string <<get>>
    + CreatedAt : DateTime <<get>>
    + IsRead : bool <<get>>
    + NotificationMessage(recipient:User, title:string, message:string)
    + MarkAsRead() : void
}
@enduml
