@startuml
class PlatformData {
    + AllUsers : List<User> <<get>> <<set>>
    + AllCourses : List<Course> <<get>> <<set>>
    + GetCourses(onlyPublic:bool) : List<Course>
    + Search(query:string) : List<Course>
    + GetUsers(role:UserRole?) : List<User>
    + SearchUsers(nicknameQuery:string) : List<User>
    + SeedData() : void
}
@enduml
