@startuml
class Student {
    + Group : string <<get>> <<set>>
    + EnrolledCourses : List<Course> <<get>> <<set>>
    +  <<event>> OnTaskSubmitted : EventHandler<StudentResponse>? 
    + Student(login:string, password:string, nickname:string, email:string, group:string)
    + RequestEnrollment(course:Course, password:string?) : bool
    + GetAvailableContent(course:Course) : List<Lesson>
    + SubmitTask(task:Task, files:List<FileModel>) : StudentResponse
    + RejectSubmission(resp:StudentResponse) : void
    + SubmitTask(response:StudentResponse) : void
    + GetLessonAverage(lesson:Lesson) : double
    + GetCourseAverage(course:Course) : double
    + GetTaskAnalytics(course:Course) : List<TaskStatusDTO>
    + Unenroll(course:Course) : void
    + EnrollInCourse(course:Course) : void
}
User <|-- Student
@enduml
