@startuml
class StudentResponse {
    + Id : Guid <<get>>
    + Author : Student <<get>>
    + TargetTask : Task <<get>>
    - _submissionDate : DateTime
    + SubmissionDate : DateTime <<get>>
    + AttachedFiles : List<FileModel> <<get>> <<set>>
    + Status : SubmissionStatus <<get>> <<set>>
    + FinalGrade : Grade? <<get>> <<set>>
    +  <<event>> OnSubmitted : EventHandler<StudentResponse>? 
    +  <<event>> OnGradeApplied : EventHandler<StudentResponse>? 
    # StudentResponse()
    + StudentResponse(author:Student, targetTask:Task)
    + ModifyFiles(file:FileModel, isAdding:bool) : void
    + Submit() : void
    + Reject() : void
    + RefreshStatus() : void
    + ApplyGrade(grade:Grade) : void
}
@enduml
